#export DATA_SOURCE_NAME='exporter:123123@(zsp.vmware.com:3306)/'
./mysql_exporter \
 --dbusername="exporter" \
 --dbpasswd="123123" \
 --collect.info_schema.tables \
 --collect.perf_schema.tablelocks \
 --collect.perf_schema.tableiowaits \
 --collect.info_schema.tablestats \
 --collect.global_status \
 --collect.global_variables \
 --collect.perf_schema.eventswaits \
 --collect.perf_schema.indexiowaits \
 --collect.info_schema.clientstats \
 --collect.info_schema.schemastats \
 --collect.slave_hosts \
 --collect.slave_status  \
 --collect.node_exporter_meminfo 
 #--collect.info_schema.userstats \
 #--collect.binlog_size \
 #--collect.perf_schema.replication_group_member_stats \
 #--collect.info_schema.query_response_time \
 #--collect.auto_increment.columns \
 #--collect.engine_innodb_status   \
 #--collect.info_schema.innodb_cmp \
 #--collect.info_schema.innodb_cmpmem \
 #--collect.info_schema.processlist \
 #--collect.info_schema.innodb_tablespaces \
 #--collect.info_schema.innodb_metrics  \
 #--collect.perf_schema.eventsstatements \
 #--collect.perf_schema.eventsstatementssum \
 #--collect.perf_schema.file_events \
 #--collect.perf_schema.file_instances \

