{
 "title": "MySQL 全局Overview",
 "description": "Dashboard from Percona Monitoring and Management project. ",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "job", "label": "job", "query": { "query": "label_values(mysql_up,job)" } },
   { "name": "mysql_count", "label": "mysql_count", "query": { "query": "query_result(count(mysql_up))" } },
   {
    "name": "mysql_running",
    "label": "mysql_running",
    "query": {
     "query": "query_result(count(mysql_up==1))"
    }
   },
   {
    "name": "mysql_failed",
    "label": "mysql_failed",
    "query": {
     "query": "query_result(count(mysql_up!=1))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## **<center><font color=\"green\">Mysql 实例总览</font></center>**"
   }
  },
  {
   "title": "Mysql实例总览表【实例总数：$mysql_count，在线实例: $mysql_running，异常实例: $mysql_failed】",
   "type": "table-old",
   "description": "Mysql 实例总览",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "expr": "mysql_up-0", "legendFormat": "{{instance}}" },
    { "expr": "mysql_global_status_uptime", "legendFormat": "运行时间" },
    {
     "expr": "rate(mysql_global_status_queries[$interval]) or irate(mysql_global_status_queries[5m])",
     "legendFormat": "QPS"
    },
    { "expr": "mysql_up-0", "legendFormat": "Healty" },
    {
     "expr": "rate(mysql_global_status_slow_queries[$interval]) or irate(mysql_global_status_slow_queries[5m])",
     "legendFormat": "慢查询数量"
    },
    {
     "expr": "max_over_time(mysql_global_status_threads_connected[5m])",
     "legendFormat": "Connected"
    },
    {
     "expr": "min_over_time(mysql_slave_status_slave_io_running[5m])",
     "legendFormat": "123"
    },
    {
     "expr": "min_over_time(mysql_slave_status_slave_sql_running[5m])",
     "legendFormat": "SlaveStatus"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "graph",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_queries[$interval]) or irate(mysql_global_status_queries[5m])",
     "legendFormat": "{{instance}} Qps"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries ",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries[$interval]) or irate(mysql_global_status_slow_queries[5m])",
     "legendFormat": "{{instance}}  Slow Queries 数量"
    },
    {
     "expr": "mysql_global_variables_long_query_time",
     "legendFormat": "{{instance}}  慢查询阈值全局变量long_query_time"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected[5m])",
     "legendFormat": "{{instance}} Connects"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "{{instance}}  Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "{{instance}}  Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_connects[$interval]) or irate(mysql_global_status_aborted_connects[5m])",
     "legendFormat": "{{instance}}  Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_clients[$interval]) or irate(mysql_global_status_aborted_clients[5m])",
     "legendFormat": "{{instance}}  Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received[$interval]) or irate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "{{instance}}  Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent[$interval]) or irate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "{{instance}}  Outbound"
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "graph",
   "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received[1h])",
     "legendFormat": "{{instance}} Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent[1h])",
     "legendFormat": "{{instance}}  Sent"
    }
   ]
  },
  { "title": "Rocksdb Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Cache Data Bytes R/W",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_bytes_read[$interval])  or irate(mysql_global_status_rocksdb_block_cache_bytes_read[5m]) ",
     "legendFormat": "{{instance}}  Reads"
    },
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_bytes_write[$interval]) or irate(mysql_global_status_rocksdb_block_cache_bytes_write[5m])",
     "legendFormat": "{{instance}}   Writes"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_hit[$interval]) or irate(mysql_global_status_rocksdb_block_cache_hit[5m])",
     "legendFormat": "{{instance}}  Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_miss[$interval]) or  irate(mysql_global_status_rocksdb_block_cache_miss[5m])",
     "legendFormat": "{{instance}}  Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_add[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add[5m])",
     "legendFormat": "{{instance}}  Added"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_add_failures[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add_failures[5m])",
     "legendFormat": "{{instance}} Added Failures"
    },
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_hit[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_hit{instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}}  Filter_hit"
    },
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_miss{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_miss{instance=~\"$host\"}[5m])",
     "legendFormat": "Filter_miss"
    },
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_add[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_add[5m])",
     "legendFormat": "{{instance}}  Filter_add"
    }
   ]
  },
  {
   "title": "Cache Index Added Rate",
   "type": "graph",
   "description": "\n\ncommand: ``Rocksdb_block_cache_index_bytes_insert``\n\n- **Description:** Bytes of index blocks added to the Block Cache.\n\ncommand:`Rocksdb_block_cache_index_bytes_evict`\n\n- **Description:** Bytes of index blocks evicted from the Block Cache.\n\ncommand:`Rocksdb_block_cache_filter_bytes_evict`\n\n- **Description:** Bytes of bloom filter blocks evicted from the Block\n\ncommand `Rocksdb_block_cache_filter_bytes_insert`\n\n- **Description:** Bytes of bloom filter blocks added to the Block",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_bytes_insert[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_insert[5m])",
     "legendFormat": "{{instance}}  Inserted"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_bytes_evict[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_evict[5m])",
     "legendFormat": "{{instance}}  Evicted"
    },
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict[5m])",
     "legendFormat": "{{instance}}  Filter_Evicted"
    },
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert[5m])",
     "legendFormat": "{{instance}}  Filter_Insert"
    }
   ]
  },
  {
   "title": "Cache Index Hit Rate",
   "type": "graph",
   "description": "command: ``Rocksdb_block_cache_index_add``\n\n- Description: Number of index blocks added to Block Cache index\n\ncommand： ``Rocksdb_block_cache_index_hit``\n\n- Description: Number of hits for the Block Cache index.\n\ncommand ： ``Rocksdb_block_cache_index_miss``\n\n- Description: Number of misses for the Block Cache index.\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_hit[$interval])  or irate(mysql_global_status_rocksdb_block_cache_index_hit[5m]) ",
     "legendFormat": "{{instance}}  Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_miss[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_miss[5m])",
     "legendFormat": "{{instance}}  Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_add[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_add[5m])",
     "legendFormat": "{{instance}}  Added"
    }
   ]
  },
  {
   "title": "Cache L0/L1",
   "type": "graph",
   "description": "use Command `` Rocksdb_get_hit_l0 ``\n- Description: Number of times reads got data from the L0 compaction layer. \\n\n\nuse command `` Rocksdb_get_hit_l1``\n- Description: Number of times reads got data from the L1 compaction layer.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_get_hit_l0[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l0[5m]) ",
     "legendFormat": "{{instance}}  L0"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_get_hit_l1[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l1[5m])",
     "legendFormat": "{{instance}}  L1"
    }
   ]
  },
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mysql Exporter Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 65 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(min_over_time(mysql_exporter_up[$interval]) or min_over_time(mysql_exporter_up[5m]))"
      }
     ]
    },
    {
     "title": "Collector Execution Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 4, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(mysql_exporter_collector_duration_seconds{instance=~\"$host\"}[$interval]) or avg_over_time(mysql_exporter_collector_duration_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "mysql_exporter Memory Distribution",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$host\"} - (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemFree_bytes{instance=\"$host\"}",
       "legendFormat": "Free"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Buffers{instance=\"$host\"}",
       "legendFormat": "Buffers"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Cached{instance=\"$host\"}",
       "legendFormat": "Cached"
      }
     ]
    }
   ]
  }
 ]
}