{
 "title": "MySQL 明细Overview",
 "description": "Dashboard from Percona Monitoring and Management project. ",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   },
   {
    "name": "version",
    "label": "version",
    "query": {
     "query": "label_values(mysql_version_info{instance=\"$host\"},version)"
    }
   },
   {
    "name": "version_comment",
    "label": "version_comment",
    "query": {
     "query": "label_values(mysql_version_info{instance=\"$host\"},version_comment)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(mysql_up,job)" } },
   { "name": "mysql_count", "label": "mysql_count", "query": { "query": "query_result(count(mysql_up))" } }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><i><font color=#5991A8><b><center>Data for </font><font color=#e68a00>$host</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1>\r\n<center><font color=\"green\">当前版本: ${version_comment}: ${version}</font></center>\r\n"
   }
  },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Mysql Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "singlestat",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "singlestat",
   "description": "Connections is the number of connection attempts (successful or not) to the MySQL server.\n\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$host\"} )"
    }
   ]
  },
  {
   "title": "Command, Handlers,SlowQueries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Slow Queries ",
     "type": "graph",
     "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_slow_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$host\"}[5m])",
       "legendFormat": "Slow Queries 数量"
      },
      {
       "expr": "mysql_global_variables_long_query_time{instance=\"$host\"}",
       "legendFormat": "慢查询阈值全局变量long_query_time"
      }
     ]
    },
    {
     "title": "Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$host\"}[5m])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "Top Command Counters Hourly",
     "type": "graph",
     "description": "**Top Command Counters Hourly**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, increase(mysql_global_status_commands_total{instance=\"$host\"}[1h])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "MySQL Handlers",
     "type": "graph",
     "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
       "legendFormat": "{{ handler }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$host\"} )",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "MySQL Aborted Connections",
     "type": "graph",
     "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_connects{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_connects{instance=\"$host\"}[5m])",
       "legendFormat": "Aborted Connects (attempts)"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_clients{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_clients{instance=\"$host\"}[5m])",
       "legendFormat": "Aborted Clients (timeout)"
      }
     ]
    },
    {
     "title": "MySQL Table Locks",
     "type": "graph",
     "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[5m])",
       "legendFormat": "Table Locks Immediate"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_waited{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_waited{instance=\"$host\"}[5m])",
       "legendFormat": "Table Locks Waited"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Largest Tables by Size",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "topk(10, sum(mysql_info_schema_table_size{instance=~\"$host\", component!=\"data_free\"}) by (schema, table)) > 0",
       "legendFormat": "{{ schema }}.{{ table }}"
      }
     ]
    },
    {
     "title": "Top 10 Largest Tables by Row Count",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "topk(10, sum(mysql_info_schema_table_rows{instance=~\"$host\"}) by (schema, table)) > 0",
       "legendFormat": "{{ schema }}.{{ table }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_sent{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "MySQL Network Usage Hourly",
     "type": "graph",
     "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_received{instance=\"$host\"}[1h])",
       "legendFormat": "Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_sent{instance=\"$host\"}[1h])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Rocksdb Cache Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_hit{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_hit{instance=~\"$host\"}[5m])",
       "legendFormat": "Hit"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_miss{instance=~\"$host\"}[$interval]) or  irate(mysql_global_status_rocksdb_block_cache_miss{instance=~\"$host\"}[5m])",
       "legendFormat": "Miss"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_add{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add{instance=~\"$host\"}[5m])",
       "legendFormat": "Added"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_add_failures{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add_failures{instance=~\"$host\"}[5m])",
       "legendFormat": "Added Failures"
      },
      {
       "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_hit{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_hit{instance=~\"$host\"}[5m])",
       "legendFormat": "Filter_hit"
      },
      {
       "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_miss{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_miss{instance=~\"$host\"}[5m])",
       "legendFormat": "Filter_miss"
      },
      {
       "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_add{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_add{instance=~\"$host\"}[5m])",
       "legendFormat": "Filter_add"
      }
     ]
    },
    {
     "title": "Cache Data Bytes R/W",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_rocksdb_block_cache_bytes_read{instance=~\"$host\"}[$interval])  or irate(mysql_global_status_rocksdb_block_cache_bytes_read{instance=~\"$host\"}[5m]) ",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(mysql_global_status_rocksdb_block_cache_bytes_write{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_bytes_write{instance=~\"$host\"}[5m])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Cache Index Hit Rate",
     "type": "graph",
     "description": "command: ``Rocksdb_block_cache_index_add``\n\n- Description: Number of index blocks added to Block Cache index\n\ncommand： ``Rocksdb_block_cache_index_hit``\n\n- Description: Number of hits for the Block Cache index.\n\ncommand ： ``Rocksdb_block_cache_index_miss``\n\n- Description: Number of misses for the Block Cache index.\n\n",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_index_hit{instance=~\"$host\"}[$interval])  or irate(mysql_global_status_rocksdb_block_cache_index_hit{instance=~\"$host\"}[5m]) ",
       "legendFormat": "Hit"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_index_miss{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_miss{instance=~\"$host\"}[5m])",
       "legendFormat": "Miss"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_index_add{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_add{instance=~\"$host\"}[5m])",
       "legendFormat": "Added"
      }
     ]
    },
    {
     "title": "Cache Index Added Rate",
     "type": "graph",
     "description": "\n\ncommand: ``Rocksdb_block_cache_index_bytes_insert``\n\n- **Description:** Bytes of index blocks added to the Block Cache.\n\ncommand:`Rocksdb_block_cache_index_bytes_evict`\n\n- **Description:** Bytes of index blocks evicted from the Block Cache.\n\ncommand:`Rocksdb_block_cache_filter_bytes_evict`\n\n- **Description:** Bytes of bloom filter blocks evicted from the Block\n\ncommand `Rocksdb_block_cache_filter_bytes_insert`\n\n- **Description:** Bytes of bloom filter blocks added to the Block",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_index_bytes_insert{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_insert{instance=~\"$host\"}[5m])",
       "legendFormat": "Inserted"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_block_cache_index_bytes_evict{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_evict{instance=~\"$host\"}[5m])",
       "legendFormat": "Evicted"
      },
      {
       "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict{instance=~\"$host\"}[5m])",
       "legendFormat": "Filter_Evicted"
      },
      {
       "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert{instance=~\"$host\"}[5m])",
       "legendFormat": "Filter_Insert"
      }
     ]
    },
    {
     "title": "Cache L0/L1",
     "type": "graph",
     "description": "use Command `` Rocksdb_get_hit_l0 ``\n- Description: Number of times reads got data from the L0 compaction layer. \\n\n\nuse command `` Rocksdb_get_hit_l1``\n- Description: Number of times reads got data from the L1 compaction layer.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_get_hit_l0{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l0{instance=~\"$host\"}[5m]) ",
       "legendFormat": "L0"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_rocksdb_get_hit_l1{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l1{instance=~\"$host\"}[5m])",
       "legendFormat": "L1"
      }
     ]
    }
   ]
  }
 ]
}